// Auto-generated by fastworker compiler — do not edit
// This file is regenerated on every build

import * as _mod_0 from '../modules/auth/api';
import * as _mod_1 from '../modules/billing/api';
import * as _mod_2 from '../modules/users/api';
import * as _mod_3 from '../modules/users/[id]/api';

export const routes = [
  {
    pattern: /^\/auth$/,
    paramNames: [],
    module: _mod_0,
    methods: ['POST'],
    routePath: '/auth',
  },
  {
    pattern: /^\/billing$/,
    paramNames: [],
    module: _mod_1,
    methods: ['GET', 'POST'],
    routePath: '/billing',
  },
  {
    pattern: /^\/users$/,
    paramNames: [],
    module: _mod_2,
    methods: ['GET', 'POST'],
    routePath: '/users',
  },
  {
    pattern: /^\/users\/(?<id>[^\/]+)$/,
    paramNames: ['id'],
    module: _mod_3,
    methods: ['GET', 'PUT', 'DELETE'],
    routePath: '/users/:id',
  },
];

export const moduleMap = new Map([
  ['auth', _mod_0],
  ['billing', _mod_1],
  ['users', _mod_2],
]);
