// Auto-generated by fastworker compiler — do not edit
// This file is regenerated on every build

import * as _mod_0 from '../modules/billing/api';

export const routes = [
  {
    pattern: /^\/billing$/,
    paramNames: [],
    module: _mod_0,
    methods: ['GET', 'POST'],
    routePath: '/billing',
  },
];

export const moduleMap = new Map([
  ['billing', _mod_0],
]);
